[build]
#   command = "cd exampleSite && hugo --gc --minify -D -b $URL"
  command = "git submodule update --remote --merge && hugo --gc --minify -D -b $DEPLOY_PRIME_URL"
  publish = "public"

[context.production.environment]
HUGO_VERSION = "0.100.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
# hugo --gc --minify -D -b $CF_PAGES_URL

[context.deploy-preview]
command = "hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.100.2"

[context.branch-deploy]
command = "npm run build && hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.100.2"
